default: dev

start:
	go run ./dia03/manha/exc-pratica-crud/cmd/main.go
dev:
	air

up-build:
	docker-compose up --build
up:
	docker-compose up -d

down:
	docker-compose down

down-v:
	docker-compose down -v

logs:
	docker-compose logs -f
	
ps:
	docker-compose ps